FROM registry.access.redhat.com/ubi8/buildah:8.10-4

ENV HOME=/home/builder
RUN mkdir -p ${HOME} && \
    chgrp -R 0 ${HOME} && \
    chmod -R g=u ${HOME}

COPY ./custom-scripts/ ${HOME}/scripts

RUN chmod +x ${HOME}/scripts/*.sh && \
    dnf install -y git-all

USER 1000680000 

ENTRYPOINT ["tail" ,"-f" ,"/dev/null"]

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:8080 || exit 1
