FROM image-registry.openshift-image-registry.svc:5000/loginapp-dev/eap-xp4-openjdk11-runtime-openshift-rhel8:4.0-73.1721172740

# Copy app to the container
COPY . /opt/app

# Set the working directory
WORKDIR /opt/app

# Set permissions
USER root
RUN chgrp -R 0 /opt/app && \
    chmod -R g=u /opt/app && \
    dnf update -y && \
    dnf install -y maven

# Build War file needed
RUN mvn install && echo "Maven build was successful" || (echo "Maven build failed" && exit 1)

# Set an environment variable for the deployments directory
ENV DEPLOYMENT_DIR=${JBOSS_HOME}/standalone/deployments

# Verify the directory exists and create it if it doesn't
RUN mkdir -p $DEPLOYMENT_DIR

# Copy the War file to the Tomcat webapps directory
USER root
RUN mv /opt/app/target/LoginWebApp.war ${DEPLOYMENT_DIR}

# Expose the default Tomcat port
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:8080 || exit 1

