FROM registry.access.redhat.com/ubi9:9.4-1123

# Install necessary packages
RUN dnf update -y && \
    dnf install -y java-11-openjdk-devel wget && \
    dnf clean all

# Download and install Tomcat
RUN wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.90/bin/apache-tomcat-9.0.90.tar.gz && \
    tar xzvf apache-tomcat-9.0.90.tar.gz && \
    mv apache-tomcat-9.0.90 /opt/tomcat && \
    rm apache-tomcat-9.0.90.tar.gz

# Set more permissive permissions
RUN chmod -R 755 /opt/tomcat && \
    chmod 755 /opt/tomcat/bin/*.sh

# Set environment variables
ENV JAVA_HOME /usr/lib/jvm/jre
ENV CATALINA_HOME /opt/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

# Copy your application WAR file
COPY /target/LoginWebApp.war $CATALINA_HOME/webapps/

# Expose the default Tomcat port
EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:8080 || exit 1

# Use numeric user ID (adjust as needed)
USER 1001

# Start Tomcat
CMD ["/opt/tomcat/bin/catalina.sh", "run"]