FROM registry.access.redhat.com/ubi8/buildah:8.10-4

ENV HOME=/home/builder
ENV BUILDER_SECRET_MOUNT_PATH=/tmp/builder-secret
RUN mkdir -p ${HOME} && \
    chgrp -R 0 ${HOME} && \
    chmod -R g=u ${HOME}

COPY ./custom-scripts/ ${HOME}/scripts

RUN chmod +x ${HOME}/scripts/*.sh && \
    dnf update -y && \
    dnf install -y git && \
    dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo && \
    dnf install -y gh

RUN mkdir -p $BUILDER_SECRET_MOUNT_PATH
VOLUME $BUILDER_SECRET_MOUNT_PATH

USER 1000680000 

ENTRYPOINT ["/bin/sh", "-c", ". ${HOME}/scripts/build-script.sh"]

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:8080 || exit 1
